# Generated by Django 3.2.4 on 2021-06-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='username',
        ),
    ]
