# Generated by Django 3.2.4 on 2021-06-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_password'),
        ('LNMtaxi', '0002_auto_20210617_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='drop',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='pickup',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contact_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
