# Generated by Django 3.2.5 on 2021-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0003_auto_20210617_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=models.CharField(default='bg-dark', max_length=20),
        ),
    ]
