# Generated by Django 3.2.4 on 2021-07-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0003_auto_20210617_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(),
        ),
    ]
