# Generated by Django 3.2.4 on 2021-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=models.CharField(default='bg-dark', max_length=20),
        ),
    ]
