# Generated by Django 3.2.4 on 2021-07-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0005_blog_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='color',
            field=models.CharField(default='#007bff', max_length=20),
        ),
    ]
