# Generated by Django 3.2.5 on 2021-07-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0004_blog_color'),
        ('LNMtaxi', '0006_alter_blog_color'),
    ]

    operations = [
    ]
