# Generated by Django 3.2.5 on 2021-07-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMtaxi', '0007_merge_0004_blog_color_0006_alter_blog_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='color',
            field=models.CharField(default='#007bff', max_length=20),
        ),
    ]
