# Generated by Django 3.2.4 on 2021-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.BigIntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
