# Generated by Django 3.2.4 on 2021-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LNMshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_imgs/'),
        ),
    ]
