# Generated by Django 3.2.4 on 2021-06-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LNMshop', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='photo',
        ),
    ]
